--- name:default
# device address in the system
dev_address: enp1s0
# number of slaves in the platform
num_slaves: 29
# system current measurement factor to convert from internal to physical units
current_factor: 41.6
# system voltage measurement factor to convert from internal to physical units
voltage_factor: 3.93

# motor slave mapping, names and configuration
motor_mapping:
    - {slave: 1, name: WHEEL_DRIVE_BR, config: *drive_config, active: true}
    - {slave: 2, name: WHEEL_STEER_BR, config: *steer_config, active: true}
    - {slave: 3, name: WHEEL_WALK_BR, config: *walk_config, active: true}
    - {slave: 4, name: WHEEL_DRIVE_BL, config: *drive_config, active: true}
    - {slave: 5, name: WHEEL_STEER_BL, config: *steer_config, active: true}
    - {slave: 6, name: WHEEL_WALK_BL, config: *walk_config, active: true}
    - {slave: 7, name: WHEEL_DRIVE_FL, config: *drive_config, active: true}
    - {slave: 8, name: WHEEL_STEER_FL, config: *steer_config, active: true}
    - {slave: 9, name: WHEEL_WALK_FL, config: *walk_config, active: true}
    - {slave: 10, name: WHEEL_DRIVE_CL, config: *drive_config, active: true}
    - {slave: 11, name: WHEEL_STEER_CL, config: *steer_config, active: true}
    - {slave: 12, name: WHEEL_WALK_CL, config: *walk_config, active: true}
    - {slave: 13, name: MAST_PAN, config: *pan_config, active: true}
    - {slave: 14, name: MAST_TILT, config: *tilt_config, active: true}
    - {slave: 15, name: WHEEL_DRIVE_CR, config: *drive_config, active: true}
    - {slave: 16, name: WHEEL_STEER_CR, config: *steer_config, active: true}
    - {slave: 17, name: WHEEL_WALK_CR, config: *walk_config, active: true}
    - {slave: 18, name: WHEEL_DRIVE_FR, config: *drive_config, active: true}
    - {slave: 19, name: WHEEL_STEER_FR, config: *steer_config, active: true}
    - {slave: 20, name: WHEEL_WALK_FR, config: *walk_config, active: true}

# fts slave mapping and names
fts_mapping:
    - {slave: 22, name: FTS_CL}
    - {slave: 23, name: FTS_FL}
    - {slave: 25, name: FTS_BL}
    - {slave: 26, name: FTS_BR}
    - {slave: 28, name: FTS_CR}
    - {slave: 29, name: FTS_FR}

# analog identifiers and desirable names
analog_input_mapping:
    - {slave: 4, name: SYSTEM_VOLTAGE}
    - {slave: 5, name: SYSTEM_CURRENT}

# passive joints identifiers and desirable names
passive_joint_mapping:
    - {slave: 0, name: LEFT_PASSIVE}
    - {slave: 1, name: RIGHT_PASSIVE}
    - {slave: 5, name: BACK_PASSIVE}

# motor parameters of the wheel drives (using relative encoder on motor)
&drive_config
  dPtpVelDefaultIncrS: 10000
  dVelMaxEncIncrS: 68267    # corresponds to 8000 rpm
  dPosLimitLowIncr: -100000000
  dBeltRatio: 1
  iSign: 1
  iEncOffsetIncr: 0
  dCurrentToTorque: 0.0181
  dDecIncrS2: 200000
  dCurrMax: 1.94
  dGearRatio: 438.46154
  bIsSteer: 0
  iEncIncrPerRevMot: 512
  dAccIncrS2: 200000
  dPosLimitHighIncr: 100000000
  dAnalogFactor: 0.00067139
  dNominalCurrent: 0.657

# motor parameters of the steer drives (using absolute encoder on load)
&steer_config
  dPtpVelDefaultIncrS: 150
  dVelMaxEncIncrS: 249    # corresponds to 8000 rpm
  dPosLimitLowIncr: -1138 # corresponds to 100 deg
  dBeltRatio: 1
  iSign: -1
  iEncOffsetIncr: 0
  dCurrentToTorque: 0.0181
  dDecIncrS2: 2000
  dCurrMax: 1.94
  dGearRatio: 1.0
  bIsSteer: 1
  iEncIncrPerRevMot: 4096
  dAccIncrS2: 2000
  dPosLimitHighIncr: 1138
  dAnalogFactor: 0.00067139
  dNominalCurrent: 0.657

# motor parameters of the walk drives (using absolute encoder on load)
&walk_config
  dPtpVelDefaultIncrS: 100
  dVelMaxEncIncrS: 249    # corresponds to 8000 rpm
  dPosLimitLowIncr: -1365 # corresponds to 120 deg
  dBeltRatio: 1
  iSign: 1
  iEncOffsetIncr: 0
  dCurrentToTorque: 0.0181
  dDecIncrS2: 2000
  dCurrMax: 1.94
  dGearRatio: 1.0
  bIsSteer: 1
  iEncIncrPerRevMot: 4096
  dAccIncrS2: 2000
  dPosLimitHighIncr: 1365
  dAnalogFactor: 0.00067139
  dNominalCurrent: 0.657

# motor parameters of the pan drive
&pan_config
  dPtpVelDefaultIncrS: 10000
  dVelMaxEncIncrS: 68267    # corresponds to 8000 rpm
  dPosLimitLowIncr: -230400 # corresponds to 135 deg
  dBeltRatio: 1
  iSign: -1
  iEncOffsetIncr: 0
  dCurrentToTorque: 0.00955
  dDecIncrS2: 1000000
  dCurrMax: 0.243
  dGearRatio: 1200 # using 1200 to correct for strange factor
  bIsSteer: 0
  iEncIncrPerRevMot: 512
  dAccIncrS2: 1000000
  dPosLimitHighIncr: 204800
  dAnalogFactor: 0
  dNominalCurrent: 0.081

# motor parameters of the tilt drive
&tilt_config
  dPtpVelDefaultIncrS: 10000
  dVelMaxEncIncrS: 68267    # corresponds to 8000 rpm
  dPosLimitLowIncr: -136533 # corresponds to 80 deg
  dBeltRatio: 1
  iSign: 1
  iEncOffsetIncr: 0
  dCurrentToTorque: 0.00955
  dDecIncrS2: 1000000
  dCurrMax: 0.243
  dGearRatio: 1200 # using 1200 to correct for strange factor
  bIsSteer: 0
  iEncIncrPerRevMot: 512
  dAccIncrS2: 1000000
  dPosLimitHighIncr: 136533
  dAnalogFactor: 0
  dNominalCurrent: 0.081
