--- name:default
# device address in the system
dev_address: enp1s0
# number of slaves in the platform
num_slaves: 29

configs:
  # motor parameters of the wheel drives (using relative encoder on motor)
  - &drive_config
    dPtpVelDefaultIncrS: 10000
    dVelMaxEncIncrS: 68267    # corresponds to 8000 rpm
    dPosLimitLowIncr: -100000000
    dBeltRatio: 1
    iSign: 1
    iEncOffsetIncr: 0
    dCurrentToTorque: 0.0181
    dDecIncrS2: 200000
    dCurrMax: 1.94
    dGearRatio: 438.46154
    bIsSteer: 0
    iEncIncrPerRevMot: 512
    dAccIncrS2: 200000
    dPosLimitHighIncr: 100000000
    dAnalogFactor: 0.00067139
    dNominalCurrent: 0.657

  # motor parameters of the steer drives (using absolute encoder on load)
  - &steer_config
    dPtpVelDefaultIncrS: 150
    dVelMaxEncIncrS: 249    # corresponds to 8000 rpm
    dPosLimitLowIncr: -1138 # corresponds to 100 deg
    dBeltRatio: 1
    iSign: -1
    iEncOffsetIncr: 0
    dCurrentToTorque: 0.0181
    dDecIncrS2: 2000
    dCurrMax: 1.94
    dGearRatio: 1.0
    bIsSteer: 1
    iEncIncrPerRevMot: 4096
    dAccIncrS2: 2000
    dPosLimitHighIncr: 1138
    dAnalogFactor: 0.00067139
    dNominalCurrent: 0.657

  # motor parameters of the walk drives (using absolute encoder on load)
  - &walk_config
    dPtpVelDefaultIncrS: 100
    dVelMaxEncIncrS: 249    # corresponds to 8000 rpm
    dPosLimitLowIncr: -1365 # corresponds to 120 deg
    dBeltRatio: 1
    iSign: 1
    iEncOffsetIncr: 0
    dCurrentToTorque: 0.0181
    dDecIncrS2: 2000
    dCurrMax: 1.94
    dGearRatio: 1.0
    bIsSteer: 1
    iEncIncrPerRevMot: 4096
    dAccIncrS2: 2000
    dPosLimitHighIncr: 1365
    dAnalogFactor: 0.00067139
    dNominalCurrent: 0.657

  # motor parameters of the pan drive
  - &pan_config
    dPtpVelDefaultIncrS: 10000
    dVelMaxEncIncrS: 68267    # corresponds to 8000 rpm
    dPosLimitLowIncr: -230400 # corresponds to 135 deg
    dBeltRatio: 1
    iSign: -1
    iEncOffsetIncr: 0
    dCurrentToTorque: 0.00955
    dDecIncrS2: 1000000
    dCurrMax: 0.243
    dGearRatio: 1200 # using 1200 to correct for strange factor
    bIsSteer: 0
    iEncIncrPerRevMot: 512
    dAccIncrS2: 1000000
    dPosLimitHighIncr: 204800
    dAnalogFactor: 0
    dNominalCurrent: 0.081

# motor parameters of the tilt drive
  - &tilt_config
    dPtpVelDefaultIncrS: 10000
    dVelMaxEncIncrS: 68267    # corresponds to 8000 rpm
    dPosLimitLowIncr: -136533 # corresponds to 80 deg
    dBeltRatio: 1
    iSign: 1
    iEncOffsetIncr: 0
    dCurrentToTorque: 0.00955
    dDecIncrS2: 1000000
    dCurrMax: 0.243
    dGearRatio: 1200 # using 1200 to correct for strange factor
    bIsSteer: 0
    iEncIncrPerRevMot: 512
    dAccIncrS2: 1000000
    dPosLimitHighIncr: 136533
    dAnalogFactor: 0
    dNominalCurrent: 0.081

# elmo drives slave mapping, names and configuration
drive_mapping:
    - {slave_id: 1,  name: ELMO_DRIVE_BR, config: *drive_config, temp_sensor: true}
    - {slave_id: 2,  name: ELMO_STEER_BR, config: *steer_config, temp_sensor: true}
    - {slave_id: 3,  name: ELMO_WALK_BR,  config: *walk_config,  temp_sensor: true}
    - {slave_id: 4,  name: ELMO_DRIVE_BL, config: *drive_config, temp_sensor: true}
    - {slave_id: 5,  name: ELMO_STEER_BL, config: *steer_config, temp_sensor: true}
    - {slave_id: 6,  name: ELMO_WALK_BL,  config: *walk_config,  temp_sensor: true}
    - {slave_id: 7,  name: ELMO_DRIVE_FL, config: *drive_config, temp_sensor: true}
    - {slave_id: 8,  name: ELMO_STEER_FL, config: *steer_config, temp_sensor: true}
    - {slave_id: 9,  name: ELMO_WALK_FL,  config: *walk_config,  temp_sensor: true}
    - {slave_id: 10, name: ELMO_DRIVE_CL, config: *drive_config, temp_sensor: true}
    - {slave_id: 11, name: ELMO_STEER_CL, config: *steer_config, temp_sensor: true}
    - {slave_id: 12, name: ELMO_WALK_CL,  config: *walk_config,  temp_sensor: true}
    - {slave_id: 13, name: ELMO_PAN,      config: *pan_config,   temp_sensor: false}
    - {slave_id: 14, name: ELMO_TILT,     config: *tilt_config,  temp_sensor: false}
    - {slave_id: 15, name: ELMO_DRIVE_CR, config: *drive_config, temp_sensor: true}
    - {slave_id: 16, name: ELMO_STEER_CR, config: *steer_config, temp_sensor: true}
    - {slave_id: 17, name: ELMO_WALK_CR,  config: *walk_config,  temp_sensor: true}
    - {slave_id: 18, name: ELMO_DRIVE_FR, config: *drive_config, temp_sensor: true}
    - {slave_id: 19, name: ELMO_STEER_FR, config: *steer_config, temp_sensor: true}
    - {slave_id: 20, name: ELMO_WALK_FR,  config: *walk_config,  temp_sensor: true}

# fts slave mapping and names
fts_mapping:
    - {slave_id: 22, name: FTS_CL}
    - {slave_id: 23, name: FTS_FL}
    - {slave_id: 25, name: FTS_BL}
    - {slave_id: 26, name: FTS_BR}
    - {slave_id: 28, name: FTS_CR}
    - {slave_id: 29, name: FTS_FR}

# joints mapping and names
joint_mapping:
    - {name: WHEEL_DRIVE_FL, drive: ELMO_DRIVE_FL, type: ACTIVE,  enabled: true}
    - {name: WHEEL_DRIVE_FR, drive: ELMO_DRIVE_FR, type: ACTIVE,  enabled: true}
    - {name: WHEEL_DRIVE_CL, drive: ELMO_DRIVE_CL, type: ACTIVE,  enabled: true}
    - {name: WHEEL_DRIVE_CR, drive: ELMO_DRIVE_CR, type: ACTIVE,  enabled: true}
    - {name: WHEEL_DRIVE_BL, drive: ELMO_DRIVE_BL, type: ACTIVE,  enabled: true}
    - {name: WHEEL_DRIVE_BR, drive: ELMO_DRIVE_BR, type: ACTIVE,  enabled: true}
    - {name: WHEEL_STEER_FL, drive: ELMO_STEER_FL, type: ACTIVE,  enabled: true}
    - {name: WHEEL_STEER_FR, drive: ELMO_STEER_FR, type: ACTIVE,  enabled: true}
    - {name: WHEEL_STEER_CL, drive: ELMO_STEER_CL, type: ACTIVE,  enabled: true}
    - {name: WHEEL_STEER_CR, drive: ELMO_STEER_CR, type: ACTIVE,  enabled: true}
    - {name: WHEEL_STEER_BL, drive: ELMO_STEER_BL, type: ACTIVE,  enabled: true}
    - {name: WHEEL_STEER_BR, drive: ELMO_STEER_BR, type: ACTIVE,  enabled: true}
    - {name: WHEEL_WALK_FL,  drive: ELMO_WALK_FL,  type: ACTIVE,  enabled: true}
    - {name: WHEEL_WALK_FR,  drive: ELMO_WALK_FR,  type: ACTIVE,  enabled: true}
    - {name: WHEEL_WALK_CL,  drive: ELMO_WALK_CL,  type: ACTIVE,  enabled: true}
    - {name: WHEEL_WALK_CR,  drive: ELMO_WALK_CR,  type: ACTIVE,  enabled: true}
    - {name: WHEEL_WALK_BL,  drive: ELMO_WALK_BL,  type: ACTIVE,  enabled: true}
    - {name: WHEEL_WALK_BR,  drive: ELMO_WALK_BR,  type: ACTIVE,  enabled: true}
    - {name: MAST_PAN,       drive: ELMO_PAN,      type: ACTIVE,  enabled: true}
    - {name: MAST_TILT,      drive: ELMO_TILT,     type: ACTIVE,  enabled: true}
    - {name: LEFT_PASSIVE,   drive: ELMO_DRIVE_FL, type: PASSIVE, enabled: false}
    - {name: RIGHT_PASSIVE,  drive: ELMO_DRIVE_FR, type: PASSIVE, enabled: false}
    - {name: BACK_PASSIVE,   drive: ELMO_DRIVE_BL, type: PASSIVE, enabled: false}
