--- name:default

## ethercat config

# ethercat network interface
network_interface: enp1s0
# number of slaves in the platform
num_slaves: 29

## slave config

drive_configs:
  # motor parameters of the wheel drives (using relative encoder on motor)
  - &drive_elmo
    min_position_rad: ~
    max_position_rad: ~
    profile_velocity_rad_sec: 0.2799
    max_profile_velocity_rad_sec: 1.9106
    max_motor_speed_rpm: 8000 # check where this is measured (encoder?)
    max_acceleration_rad_sec_sec: 2.7988
    max_deceleration_rad_sec_sec: 2.7988
    motor_rated_torque_nm: 0.011
    motor_rated_current_amp: 0.657
    max_current_amp: 1.94
    gear_ratio: 438.4615
    position_encoder_resolution: 512
    velocity_encoder_resolution: 512

  # motor parameters of the steer drives (using absolute encoder on load)
  - &steer_elmo
    dPtpVelDefaultIncrS: 150
    dVelMaxEncIncrS: 249    # corresponds to 8000 rpm
    dPosLimitLowIncr: -1138 # corresponds to 100 deg
    dBeltRatio: 1
    iSign: -1
    iEncOffsetIncr: 0
    dCurrentToTorque: 0.0181
    dDecIncrS2: 2000
    dCurrMax: 1.94
    dGearRatio: 1.0
    bIsSteer: 1
    iEncIncrPerRevMot: 4096
    dAccIncrS2: 2000
    dPosLimitHighIncr: 1138
    dAnalogFactor: 0.00067139
    dNominalCurrent: 0.657

  # motor parameters of the walk drives (using absolute encoder on load)
  - &walk_elmo
    dPtpVelDefaultIncrS: 100
    dVelMaxEncIncrS: 249    # corresponds to 8000 rpm
    dPosLimitLowIncr: -1365 # corresponds to 120 deg
    dBeltRatio: 1
    iSign: 1
    iEncOffsetIncr: 0
    dCurrentToTorque: 0.0181
    dDecIncrS2: 2000
    dCurrMax: 1.94
    dGearRatio: 1.0
    bIsSteer: 1
    iEncIncrPerRevMot: 4096
    dAccIncrS2: 2000
    dPosLimitHighIncr: 1365
    dAnalogFactor: 0.00067139
    dNominalCurrent: 0.657

  # motor parameters of the pan drive
  - &pan_elmo
    dPtpVelDefaultIncrS: 10000
    dVelMaxEncIncrS: 68267    # corresponds to 8000 rpm
    dPosLimitLowIncr: -230400 # corresponds to 135 deg
    dBeltRatio: 1
    iSign: -1
    iEncOffsetIncr: 0
    dCurrentToTorque: 0.00955
    dDecIncrS2: 1000000
    dCurrMax: 0.243
    dGearRatio: 1200 # using 1200 to correct for strange factor
    bIsSteer: 0
    iEncIncrPerRevMot: 512
    dAccIncrS2: 1000000
    dPosLimitHighIncr: 204800
    dAnalogFactor: 0
    dNominalCurrent: 0.081

  # motor parameters of the tilt drive
  - &tilt_elmo
    dPtpVelDefaultIncrS: 10000
    dVelMaxEncIncrS: 68267    # corresponds to 8000 rpm
    dPosLimitLowIncr: -136533 # corresponds to 80 deg
    dBeltRatio: 1
    iSign: 1
    iEncOffsetIncr: 0
    dCurrentToTorque: 0.00955
    dDecIncrS2: 1000000
    dCurrMax: 0.243
    dGearRatio: 1200 # using 1200 to correct for strange factor
    bIsSteer: 0
    iEncIncrPerRevMot: 512
    dAccIncrS2: 1000000
    dPosLimitHighIncr: 136533
    dAnalogFactor: 0
    dNominalCurrent: 0.081

# elmo slave mapping, names and configuration
drive_mapping:
    - {slave_id: 1,  name: ELMO_DRIVE_BR, config: *drive_elmo}
    - {slave_id: 2,  name: ELMO_STEER_BR, config: *steer_elmo}
    - {slave_id: 3,  name: ELMO_WALK_BR,  config: *walk_elmo}
    - {slave_id: 4,  name: ELMO_DRIVE_BL, config: *drive_elmo}
    - {slave_id: 5,  name: ELMO_STEER_BL, config: *steer_elmo}
    - {slave_id: 6,  name: ELMO_WALK_BL,  config: *walk_elmo}
    - {slave_id: 7,  name: ELMO_DRIVE_FL, config: *drive_elmo}
    - {slave_id: 8,  name: ELMO_STEER_FL, config: *steer_elmo}
    - {slave_id: 9,  name: ELMO_WALK_FL,  config: *walk_elmo}
    - {slave_id: 10, name: ELMO_DRIVE_CL, config: *drive_elmo}
    - {slave_id: 11, name: ELMO_STEER_CL, config: *steer_elmo}
    - {slave_id: 12, name: ELMO_WALK_CL,  config: *walk_elmo}
    - {slave_id: 13, name: ELMO_PAN,      config: *pan_elmo}
    - {slave_id: 14, name: ELMO_TILT,     config: *tilt_elmo}
    - {slave_id: 15, name: ELMO_DRIVE_CR, config: *drive_elmo}
    - {slave_id: 16, name: ELMO_STEER_CR, config: *steer_elmo}
    - {slave_id: 17, name: ELMO_WALK_CR,  config: *walk_elmo}
    - {slave_id: 18, name: ELMO_DRIVE_FR, config: *drive_elmo}
    - {slave_id: 19, name: ELMO_STEER_FR, config: *steer_elmo}
    - {slave_id: 20, name: ELMO_WALK_FR,  config: *walk_elmo}

# force torque sensor slave mapping and names
fts_mapping:
    - {slave_id: 22, name: FTS_CL}
    - {slave_id: 23, name: FTS_FL}
    - {slave_id: 25, name: FTS_BL}
    - {slave_id: 26, name: FTS_BR}
    - {slave_id: 28, name: FTS_CR}
    - {slave_id: 29, name: FTS_FR}

## joint config

joint_configs:
  - &drive_joint
    flip_sign: false
    min_position_rad:
    max_position_rad:
    max_velocity_rad_sec:
    max_torque_nm:

  - &steer_joint
    flip_sign: false
    min_position_rad:
    max_position_rad:
    max_velocity_rad_sec:
    max_torque_nm:

  - &walk_joint
    flip_sign: false
    min_position_rad:
    max_position_rad:
    max_velocity_rad_sec:
    max_torque_nm:

  - &pan_joint
    flip_sign: false
    min_position_rad:
    max_position_rad:
    max_velocity_rad_sec:
    max_torque_nm:

  - &tilt_joint
    flip_sign: false
    min_position_rad:
    max_position_rad:
    max_velocity_rad_sec:
    max_torque_nm:

# active joint names, mapping to drives and configuration
active_joint_mapping:
    - {name: WHEEL_DRIVE_FL, drive: ELMO_DRIVE_FL, config: *drive_joint, enabled: true}
    - {name: WHEEL_DRIVE_FR, drive: ELMO_DRIVE_FR, config: *drive_joint, enabled: true}
    - {name: WHEEL_DRIVE_CL, drive: ELMO_DRIVE_CL, config: *drive_joint, enabled: true}
    - {name: WHEEL_DRIVE_CR, drive: ELMO_DRIVE_CR, config: *drive_joint, enabled: true}
    - {name: WHEEL_DRIVE_BL, drive: ELMO_DRIVE_BL, config: *drive_joint, enabled: true}
    - {name: WHEEL_DRIVE_BR, drive: ELMO_DRIVE_BR, config: *drive_joint, enabled: true}
    - {name: WHEEL_STEER_FL, drive: ELMO_STEER_FL, config: *steer_joint, enabled: true}
    - {name: WHEEL_STEER_FR, drive: ELMO_STEER_FR, config: *steer_joint, enabled: true}
    - {name: WHEEL_STEER_CL, drive: ELMO_STEER_CL, config: *steer_joint, enabled: true}
    - {name: WHEEL_STEER_CR, drive: ELMO_STEER_CR, config: *steer_joint, enabled: true}
    - {name: WHEEL_STEER_BL, drive: ELMO_STEER_BL, config: *steer_joint, enabled: true}
    - {name: WHEEL_STEER_BR, drive: ELMO_STEER_BR, config: *steer_joint, enabled: true}
    - {name: WHEEL_WALK_FL,  drive: ELMO_WALK_FL,  config: *walk_joint,  enabled: true}
    - {name: WHEEL_WALK_FR,  drive: ELMO_WALK_FR,  config: *walk_joint,  enabled: true}
    - {name: WHEEL_WALK_CL,  drive: ELMO_WALK_CL,  config: *walk_joint,  enabled: true}
    - {name: WHEEL_WALK_CR,  drive: ELMO_WALK_CR,  config: *walk_joint,  enabled: true}
    - {name: WHEEL_WALK_BL,  drive: ELMO_WALK_BL,  config: *walk_joint,  enabled: true}
    - {name: WHEEL_WALK_BR,  drive: ELMO_WALK_BR,  config: *walk_joint,  enabled: true}
    - {name: MAST_PAN,       drive: ELMO_PAN,      config: *pan_joint,   enabled: true}
    - {name: MAST_TILT,      drive: ELMO_TILT,     config: *tilt_joint,  enabled: true}

# passive joint names and mapping to drives
passive_joint_mapping:
    - {name: LEFT_PASSIVE,   drive: ELMO_DRIVE_FL, enabled: false}
    - {name: RIGHT_PASSIVE,  drive: ELMO_DRIVE_FR, enabled: false}
    - {name: BACK_PASSIVE,   drive: ELMO_DRIVE_BL, enabled: false}
